import * as pulumi from "@pulumi/pulumi";
import * as aws from "@pulumi/aws";

export const codebuild_policy = new aws.iam.Policy(
  "codebuild_policy",
  {
    description: "Policy used in trust relationship with CodeBuild",
    name: "codebuild_policy",
    path: "/service-role/",
    policy: JSON.stringify({
      Statement: [
        {
          Action: [
            "ecr:GetRegistryPolicy",
            "ecr:DescribeRegistry",
            "ecr:DescribePullThroughCacheRules",
            "ecr:GetAuthorizationToken",
            "ecr:PutRegistryScanningConfiguration",
            "ecr:CreatePullThroughCacheRule",
            "ecr:DeletePullThroughCacheRule",
            "ecr:GetRegistryScanningConfiguration",
            "ecr:PutReplicationConfiguration",
          ],
          Effect: "Allow",
          Resource: "*",
        },
        {
          Action: [
            "ecr:PutImageTagMutability",
            "ecr:StartImageScan",
            "ecr:DescribeImageReplicationStatus",
            "ecr:ListTagsForResource",
            "ecr:BatchDeleteImage",
            "ecr:UploadLayerPart",
            "ecr:BatchGetRepositoryScanningConfiguration",
            "ecr:ListImages",
            "ecr:DeleteRepository",
            "codebuild:CreateReport",
            "logs:CreateLogStream",
            "codebuild:UpdateReport",
            "ecr:CompleteLayerUpload",
            "codebuild:BatchPutCodeCoverages",
            "ecr:TagResource",
            "ecr:DescribeRepositories",
            "ecr:BatchCheckLayerAvailability",
            "ecr:ReplicateImage",
            "ecr:GetLifecyclePolicy",
            "ecr:PutLifecyclePolicy",
            "ecr:DescribeImageScanFindings",
            "ecr:CreateRepository",
            "ecr:GetLifecyclePolicyPreview",
            "ecr:GetDownloadUrlForLayer",
            "ecr:PutImageScanningConfiguration",
            "s3:GetBucketAcl",
            "logs:CreateLogGroup",
            "logs:PutLogEvents",
            "ecr:DeleteLifecyclePolicy",
            "ecr:PutImage",
            "s3:PutObject",
            "s3:GetObject",
            "codebuild:CreateReportGroup",
            "ecr:UntagResource",
            "ecr:BatchGetImage",
            "ecr:DescribeImages",
            "ecr:StartLifecyclePolicyPreview",
            "s3:GetBucketLocation",
            "ecr:InitiateLayerUpload",
            "codebuild:BatchPutTestCases",
            "s3:GetObjectVersion",
            "ecr:GetRepositoryPolicy",
          ],
          Effect: "Allow",
          Resource: "*",
        },
      ],
      Version: "2012-10-17",
    }),
  },
  {
    protect: true,
  }
);
